version: '3.8'

services:
  django_app:
    container_name: django_app
    restart: always
    build: 
      context: ../../django_app
      dockerfile: Dockerfile
    command: gunicorn django_app.wsgi:application --bind 0.0.0.0:${BACKEND_PORT:-8000}
    volumes:
      - ../../django_app/static:/usr/src/django_app/static
      - media_volume:/usr/src/django_app/media
    ports:
      - ${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}
    environment:
      BACKEND_PORT: ${BACKEND_PORT:-8000}
      DEBUG: ${DEBUG:-1}
      SECRET_KEY: ${SECRET_KEY:-django-insecure-change-me}
      DJANGO_ALLOWED_HOSTS: "${DJANGO_ALLOWED_HOSTS:-localhost 127.0.0.1}"
      POSTGRES_ENGINE: ${POSTGRES_ENGINE:-django.db.backends.postgresql}
      POSTGRES_DB: ${POSTGRES_DB:-agaba}
      POSTGRES_USER: ${POSTGRES_USER:-agaba}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-agaba}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      DJANGO_CREATE_SUPERUSER: ${DJANGO_CREATE_SUPERUSER:-1}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME:-admin}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD:-admin}
    depends_on:
      - db

  db:
    # image: postgres:16
    container_name: db
    restart: always
    build: 
      context: ../../db
      dockerfile: Dockerfile
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-agaba}
      POSTGRES_USER: ${POSTGRES_USER:-agaba}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-agaba}

  nginx-proxy:
    container_name: nginx-proxy
    restart: always
    build:
      context: ../../nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
      - 80:80
    volumes:
      - ../../django_app/static:/usr/src/django_app/static
      - media_volume:/usr/src/django_app/media
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - django_app
  acme-companion:
    container_name: acme-companion
    restart: always
    image: nginxproxy/acme-companion
    environment:
      DEFAULT_EMAIL: ${DEFAULT_EMAIL:-local@example.com}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
      
volumes:
  postgres_data:
  media_volume:
  certs:
  html:
  vhost:
  acme:
